export const skillsArray = [
  'JavaScript',
  'React',
  'Typescript',
  'CSS',
  'HTML5',
  'Next.js',
  'Astro',
  'Vite',
  'Node.js',
  'Nest.js',
  'Mongoose',
  'Sequelize',
  'TypeORM',
  'GraphQL',
  'Express.js',
  'Passport',
  'JWT',
  'Bcrypt',
  'ZOD',
  'Yup',
  'Wordpress',
  'Shopify',
  'Sanity.io',
  'Graph CMS',
  'SQL',
  'PostgreSQL',
  'Mongo DB',
  'Redis',
  'Jest',
  'Vitest',
];

export const softSkillsArray = [
  'Comunicación efectiva',
  'Trabajo en equipo',
  'Resolución de problemas',
  'Adaptabilidad',
  'Creatividad',
  'Gestión de tiempo',
  'Pensamiento crítico',
];
